### ISSUE TITLE
Построение перпендикулярной прямой

### ISSUE THREAD

**Issue by maximpetrov** [AndreiChugunov/Geometry#4]
У Вас ошибка при вычислении коэффициентов перпендикулярной прямой. И назовите метод нормально.

**Comment by maximpetrov** [comment]
У Вас всё ещё ошибка в вычислении коэффициентов

**Comment by maximpetrov** [comment]
Вы сделали ещё хуже

**Comment by maximpetrov** [comment]
Вы вернули как было изначально, там всё ещё ошибка.

**Comment by AndreiChugunov** [comment]
A(y-y1)-B(x-x1)=0

Источник:  http://math.semestr.ru/line/perpendicular.php
© semestr.ru - Образовательный портал: учебные материалы и онлайн-калькуляторы
A(y-y1)-B(x-x1)=0

Источник:  http://math.semestr.ru/line/perpendicular.php
© semestr.ru - Образовательный портал: учебные материалы и онлайн-калькуляторы
A(y-y1)-B(x-x1)=0

Источник:  http://math.semestr.ru/line/perpendicular.php
© semestr.ru - Образовательный портал: учебные материалы и онлайн-калькуляторы
A(y-y1)-B(x-x1)=0

Источник:  http://math.semestr.ru/line/perpendicular.php
© semestr.ru - Образовательный портал: учебные материалы и онлайн-калькуляторы
A(y-y1)-B(x-x1)=0

Источник:  http://math.semestr.ru/line/perpendicular.php
© semestr.ru - Образовательный портал: учебные материалы и онлайн-калькуляторы Не могу понять, где ошибка. Считаю по формуле: y-y1=(-1/k) \* (x-x1) , где (x1,y1)-координаты точки

**Comment by maximpetrov** [comment]
Формула правильная, но Вы перепутали коэффициенты

**Comment by AndreiChugunov** [comment]
Все понял, где была ошибка. Действительно не заметил
